// Pulls content from Sanity at build/dev time and writes it into src/data/*.ts,
// which the app imports normally — no runtime fetch, no loading states.
// Run automatically via the "predev" / "prebuild" npm scripts.
import { createClient } from '@sanity/client';
import { createImageUrlBuilder } from '@sanity/image-url';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

try {
  process.loadEnvFile('.env.local');
} catch {
  // .env.local is optional locally; CI supplies env vars directly.
}

const projectId = process.env.SANITY_PROJECT_ID;
const dataset = process.env.SANITY_DATASET || 'production';

if (!projectId) {
  console.warn(
    '[fetch-content] SANITY_PROJECT_ID not set — skipping fetch, keeping existing src/data/*.ts as-is.'
  );
  process.exit(0);
}

const client = createClient({ projectId, dataset, apiVersion: '2024-01-01', useCdn: true });
const builder = createImageUrlBuilder(client);
const urlFor = (source) => (source ? builder.image(source).url() : '');

const DATA_DIR = path.join(import.meta.dirname, '..', 'src', 'data');

const GENERATED_HEADER = (source) =>
  `// AUTO-GENERATED by scripts/fetch-content.mjs from Sanity (${source}).\n` +
  `// Do not edit by hand — edit content in Sanity Studio and rerun \`npm run dev\` or \`npm run build\`.\n`;

async function writeProjects() {
  const docs = await client.fetch(`*[_type == "project"] | order(order asc){
    "slug": slug.current, title, tagline, shortDescription, category, tags, year,
    coverImage, featured, role,
    links[]{label, url}
  }`);

  const projects = docs.map((d) => ({
    slug: d.slug ?? '',
    title: d.title ?? '',
    tagline: d.tagline ?? '',
    shortDescription: d.shortDescription ?? '',
    category: d.category ?? '',
    tags: d.tags ?? [],
    year: d.year ?? new Date().getFullYear(),
    coverImage: urlFor(d.coverImage),
    featured: Boolean(d.featured),
    role: d.role ?? '',
    links: d.links ?? [],
  }));

  const content =
    GENERATED_HEADER('project documents') +
    `import type { Project } from '../types';\n\n` +
    `export const projects: Project[] = ${JSON.stringify(projects, null, 2)};\n\n` +
    `export const featuredProjects: Project[] = projects.filter((p) => p.featured);\n`;

  await writeFile(path.join(DATA_DIR, 'projects.ts'), content);
}

async function writeAbout() {
  const doc = await client.fetch(`*[_type == "about"][0]{
    aboutIntro, aboutFull,
    skills[]{name, category},
    values[]{title, body},
    quickFacts{city, years, background, currentRole, education}
  }`);

  const about = {
    aboutIntro: doc?.aboutIntro ?? '',
    aboutFull: doc?.aboutFull ?? '',
    skills: doc?.skills ?? [],
    values: doc?.values ?? [],
    quickFacts: doc?.quickFacts ?? { city: '', years: '', background: '', currentRole: '', education: '' },
  };

  const content =
    GENERATED_HEADER('the "about" document') +
    `import type { Skill, Value, QuickFacts } from '../types';\n\n` +
    `export const aboutIntro: string = ${JSON.stringify(about.aboutIntro)};\n` +
    `export const aboutFull: string = ${JSON.stringify(about.aboutFull)};\n` +
    `export const skills: Skill[] = ${JSON.stringify(about.skills, null, 2)};\n` +
    `export const values: Value[] = ${JSON.stringify(about.values, null, 2)};\n` +
    `export const quickFacts: QuickFacts = ${JSON.stringify(about.quickFacts, null, 2)};\n`;

  await writeFile(path.join(DATA_DIR, 'about.ts'), content);
}

async function writeMentorship() {
  const docs = await client.fetch(`*[_type == "mentorshipTier"] | order(order asc){
    "id": tierId.current, type, name, tagline, price, duration, includes, forWhom,
    cta{label, href}
  }`);

  const tiers = docs.map((d) => ({
    id: d.id ?? '',
    type: d.type ?? 'paid',
    name: d.name ?? '',
    tagline: d.tagline ?? '',
    price: d.price || null,
    duration: d.duration ?? '',
    includes: d.includes ?? [],
    forWhom: d.forWhom ?? '',
    cta: d.cta ?? { label: '', href: '' },
  }));

  const content =
    GENERATED_HEADER('mentorshipTier documents') +
    `import type { MentorshipTier } from '../types';\n\n` +
    `export const mentorshipTiers: MentorshipTier[] = ${JSON.stringify(tiers, null, 2)};\n`;

  await writeFile(path.join(DATA_DIR, 'mentorship.ts'), content);
}

async function writeNavigation() {
  const doc = await client.fetch(`*[_type == "navigation"][0]{
    navItems[]{label, href, isExternal},
    socialLinks[]{label, href, icon}
  }`);

  const navItems = (doc?.navItems ?? []).map((n) => ({
    label: n.label ?? '',
    href: n.href ?? '',
    ...(n.isExternal ? { isExternal: true } : {}),
  }));
  const socialLinks = (doc?.socialLinks ?? []).map((s) => ({
    label: s.label ?? '',
    href: s.href ?? '',
    icon: s.icon ?? '',
  }));

  const content =
    GENERATED_HEADER('the "navigation" document') +
    `import type { NavItem, SocialLink } from '../types';\n\n` +
    `export const navItems: NavItem[] = ${JSON.stringify(navItems, null, 2)};\n` +
    `export const socialLinks: SocialLink[] = ${JSON.stringify(socialLinks, null, 2)};\n`;

  await writeFile(path.join(DATA_DIR, 'navigation.ts'), content);
}

await Promise.all([writeProjects(), writeAbout(), writeMentorship(), writeNavigation()]);
console.log(`[fetch-content] Wrote src/data/*.ts from Sanity project "${projectId}" (dataset: ${dataset}).`);
