// AUTO-GENERATED by scripts/fetch-content.mjs from Sanity (the "about" document).
// Do not edit by hand — edit content in Sanity Studio and rerun `npm run dev` or `npm run build`.
import type { Skill, Value, QuickFacts } from '../types';

export const aboutIntro: string = "I'm Vivek Ramachandran, a product designer and strategist who combines craft, systems thinking, and business impact.";
export const aboutFull: string = "I've spent the last 8+ years designing products that millions of people use every day - from zero-to-one consumer apps to enterprise platforms with global scale. I work across the full product lifecycle: from early discovery and strategy through to shipping polished, production-ready experiences.\n\nMy background: I started as a software engineer (machine learning developer) and then transitioned into product design and management, which means I think in systems, speak the language of engineers and stakeholders equally well, and obsess over the things that sit between the pixels - the logic, the constraints, and the outcomes.\n\nWhen I'm not designing, I'm mentoring the next generation of product designers, business analysts, start-up entrepreneurs, and writing articles at the intersection of strategy and business.\n\nI believe that great design is invisible when it's working and unforgettable when it's not.";
export const skills: Skill[] = [
  {
    "category": "craft",
    "name": "Product Design"
  },
  {
    "category": "craft",
    "name": "Design Systems"
  },
  {
    "category": "craft",
    "name": "UX Research"
  },
  {
    "category": "craft",
    "name": "Interaction Design"
  },
  {
    "category": "craft",
    "name": "Prototyping"
  },
  {
    "category": "craft",
    "name": "Visual Design"
  },
  {
    "category": "strategy",
    "name": "Product Strategy"
  },
  {
    "category": "strategy",
    "name": "Roadmapping"
  },
  {
    "category": "strategy",
    "name": "Stakeholder Alignment"
  },
  {
    "category": "strategy",
    "name": "Design Leadership"
  },
  {
    "category": "tools",
    "name": "Figma"
  },
  {
    "category": "tools",
    "name": "Framer"
  },
  {
    "category": "tools",
    "name": "React"
  },
  {
    "category": "tools",
    "name": "TypeScript"
  },
  {
    "category": "tools",
    "name": "Storybook"
  },
  {
    "category": "tools",
    "name": "Notion"
  },
  {
    "category": "ai",
    "name": "ChatGPT / Claude"
  },
  {
    "category": "ai",
    "name": "Midjourney"
  },
  {
    "category": "ai",
    "name": "Cursor"
  },
  {
    "category": "ai",
    "name": "Copilot & Automation "
  },
  {
    "category": "ai",
    "name": "Ollama LLM & Offline Hosting"
  },
  {
    "category": "ai",
    "name": "AI-Assisted Prototyping"
  }
];
export const values: Value[] = [
  {
    "body": "Great products begin with a clear direction. I align teams around a shared vision before focusing on delivery.",
    "title": "Vision before execution"
  },
  {
    "body": "Every roadmap, feature, and investment should create meaningful value for customers and measurable value for the business.",
    "title": "Customer value drives decisions"
  },
  {
    "body": "Strong teams scale through frameworks, processes, and shared ownership not individual heroics.",
    "title": "Build systems, not dependencies"
  },
  {
    "body": "I focus on business impact, customer outcomes, and long-term product health rather than output alone.",
    "title": "Outcomes define success"
  },
  {
    "body": "Leadership is turning uncertainty into direction. I bring structure, priorities, and confidence to complex challenges.",
    "title": "Create clarity in ambiguity"
  },
  {
    "body": "Products grow when people grow. I invest in mentorship, collaboration, and building high-performing teams.",
    "title": "Elevate people and culture"
  }
];
export const quickFacts: QuickFacts = {
  "background": "Software, UI/UX Design, Product Management",
  "city": "Chennai, TN, India",
  "currentRole": "Lead UX Designer",
  "education": "B.Tech IT, M.sc AI & ML, IDX & CalsArts UX Design & Specialization, IIM Kozhikode Product Management, IIT Patna Agentic AI and Generative AI",
  "years": "8+ years in product design"
};
