// AUTO-GENERATED by scripts/fetch-content.mjs from Sanity (mentorshipTier documents).
// Do not edit by hand — edit content in Sanity Studio and rerun `npm run dev` or `npm run build`.
import type { MentorshipTier } from '../types';

export const mentorshipTiers: MentorshipTier[] = [
  {
    "id": "hot-topic",
    "type": "free",
    "name": "Hot Topic 🔥",
    "tagline": "Join me for an in-depth discussion on a hot topic of your choice, where we can delve into various aspects of Design and Management Path",
    "price": "0",
    "duration": "45 Min - 60 Min",
    "includes": [
      "Project Review",
      "Interview Prep",
      "Career Break ",
      "ATS Resume Prep ",
      "Career Roadmap",
      "Professional Switching",
      "Corporate Management",
      "Financial Management",
      "Personal Management",
      "Upskill Development "
    ],
    "forWhom": "Intermediate and Advance people seeking to explore ideas and discuss them with professionals.",
    "cta": {
      "href": "https://adplist.org/mentors/vivek-ramachandran?session=hot-topic-976f-msizxove",
      "label": "Book Slot (Free! Limited)"
    }
  },
  {
    "id": "caffeine-mode",
    "type": "free",
    "name": "Caffeine mode ☕️",
    "tagline": "Let's Connect: 1:1 Session (Free!). Join me for an informal discussion, where we can explore a range of topics, including:",
    "price": "0",
    "duration": "30 Min",
    "includes": [
      "UI/UX Design",
      "Product Design Strategy",
      "AI and Automation",
      "Design System",
      "Career Development",
      "Personal Development",
      "Skills & Tools"
    ],
    "forWhom": "Beginners and intermediate users seeking to explore ideas and discuss them with professionals.",
    "cta": {
      "href": "https://adplist.org/mentors/vivek-ramachandran?session=caffeine-mode-976f-msizo5in",
      "label": "Book Slot"
    }
  }
];
