// AUTO-GENERATED by scripts/fetch-content.mjs from Sanity (the "navigation" document).
// Do not edit by hand — edit content in Sanity Studio and rerun `npm run dev` or `npm run build`.
import type { NavItem, SocialLink } from '../types';

export const navItems: NavItem[] = [
  {
    "label": "Work",
    "href": "/works"
  },
  {
    "label": "About",
    "href": "/about"
  },
  {
    "label": "Mentorship",
    "href": "/mentorship"
  }
];
export const socialLinks: SocialLink[] = [
  {
    "label": "GitHub",
    "href": "https://github.com/vivekrbot",
    "icon": "github"
  },
  {
    "label": "LinkedIn",
    "href": "https://www.linkedin.com/in/itsvivekramachandran/",
    "icon": "linkedin"
  },
  {
    "label": "Dribbble",
    "href": "https://dribbble.com/itsvivekdesign",
    "icon": "dribbble"
  },
  {
    "label": "Medium",
    "href": "https://medium.com/@vivekramachandran",
    "icon": "medium"
  },
  {
    "label": "ADPList",
    "href": "https://adplist.org/mentors/vivek-ramachandran",
    "icon": "adplist"
  }
];
