// AUTO-GENERATED by scripts/fetch-content.mjs from Sanity (project documents).
// Do not edit by hand — edit content in Sanity Studio and rerun `npm run dev` or `npm run build`.
import type { Project } from '../types';

export const projects: Project[] = [];

export const featuredProjects: Project[] = projects.filter((p) => p.featured);
